import type { Scheme, SchemeCategory } from '@/types';

/**
 * 30 realistic Delhi government schemes across 7 categories.
 */
export const SCHEMES_SEED: Omit<Scheme, 'id' | 'created_at'>[] = [
  {
    title_en: "Delhi Ladli Scheme",
    title_hi: "दिल्ली लाडली योजना",
    short_description_en: "Financial assistance to girl children born in Delhi to promote education.",
    short_description_hi: "शिक्षा को बढ़ावा देने के लिए दिल्ली में पैदा हुई बालिकाओं को वित्तीय सहायता।",
    description_en: "Financial assistance to girl children born in Delhi to promote education and prevent female foeticide. The amount is given in stages.",
    description_hi: "शिक्षा को बढ़ावा देने और कन्या भ्रूण हत्या को रोकने के लिए दिल्ली में पैदा हुई बालिकाओं को वित्तीय सहायता। राशि चरणों में दी जाती है।",
    eligibility_en: "Born in Delhi, family annual income must be below Rs 1,00,000, must be enrolled in a recognized school.",
    eligibility_hi: "दिल्ली में जन्म, पारिवारिक वार्षिक आय 1,00,000 रुपये से कम होनी चाहिए, मान्यता प्राप्त स्कूल में नामांकित होना चाहिए।",
    benefits_en: "Financial assistance in stages up to Rs 11,000.",
    benefits_hi: "11,000 रुपये तक के चरणों में वित्तीय सहायता।",
    apply_url: "https://wcddel.in/ladli.html",
    application_link: "https://edistrict.delhigovt.nic.in/",
    department: "Department of Women & Child Development",
    category: "women",
    target_groups: ["Girls", "Students"],
    tags: ["education", "financial-assistance", "girl-child"],
    required_documents: ["Birth Certificate", "Aadhaar Card", "Income Certificate", "Passport size photographs"],
    min_age: 0,
    max_age: 18,
    gender: "female",
    occupation: null,
    social_category: null,
    has_disability: false,
    max_income: 100000,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Jai Bhim Mukhyamantri Pratibha Vikas Yojana",
    title_hi: "जय भीम मुख्यमंत्री प्रतिभा विकास योजना",
    short_description_en: "Free coaching for competitive exams for SC/ST/OBC/EWS students.",
    short_description_hi: "SC/ST/OBC/EWS छात्रों के लिए प्रतियोगी परीक्षाओं के लिए मुफ्त कोचिंग।",
    description_en: "Provides free coaching through empanelled centers to students belonging to SC, ST, OBC, and EWS categories preparing for competitive examinations.",
    description_hi: "प्रतियोगी परीक्षाओं की तैयारी कर रहे SC, ST, OBC और EWS श्रेणियों के छात्रों को सूचीबद्ध केंद्रों के माध्यम से मुफ्त कोचिंग प्रदान करता है।",
    eligibility_en: "Resident of Delhi, passed 10th and 12th from Delhi schools, family income below Rs 8 Lakhs p.a.",
    eligibility_hi: "दिल्ली का निवासी, दिल्ली के स्कूलों से 10वीं और 12वीं पास, पारिवारिक आय 8 लाख रुपये प्रति वर्ष से कम।",
    benefits_en: "Free coaching and a stipend of Rs 2,500 per month.",
    benefits_hi: "मुफ्त कोचिंग और 2,500 रुपये प्रति माह का वजीफा।",
    apply_url: "https://scstwelfare.delhigovt.nic.in/",
    application_link: "https://edistrict.delhigovt.nic.in/",
    department: "Department for the Welfare of SC/ST/OBC",
    category: "students",
    target_groups: ["Students", "SC/ST/OBC", "EWS"],
    tags: ["education", "coaching", "stipend"],
    required_documents: ["Aadhaar Card", "Caste Certificate", "Income Certificate", "Marksheets"],
    min_age: 15,
    max_age: 30,
    gender: null,
    occupation: "student",
    social_category: "SC/ST/OBC/EWS",
    has_disability: false,
    max_income: 800000,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Free Supply of Textbooks to Students",
    title_hi: "छात्रों को पाठ्यपुस्तकों की मुफ्त आपूर्ति",
    short_description_en: "Free textbooks or cash subsidy for students in government schools.",
    short_description_hi: "सरकारी स्कूलों में छात्रों के लिए मुफ्त पाठ्यपुस्तकें या नकद सब्सिडी।",
    description_en: "Provision of free text books or cash in lieu of text books to all the students studying in Govt. and Govt. Aided Schools.",
    description_hi: "सरकारी और सरकारी सहायता प्राप्त स्कूलों में पढ़ने वाले सभी छात्रों को मुफ्त पाठ्यपुस्तकें या पाठ्यपुस्तकों के बदले नकद प्रदान करना।",
    eligibility_en: "Must be a student enrolled in a Delhi Government or Aided School in classes Nursery to 12th.",
    eligibility_hi: "नर्सरी से 12वीं कक्षा में दिल्ली सरकार या सहायता प्राप्त स्कूल में नामांकित छात्र होना चाहिए।",
    benefits_en: "Free textbooks or equivalent cash transfer.",
    benefits_hi: "मुफ्त पाठ्यपुस्तकें या समकक्ष नकद हस्तांतरण।",
    apply_url: "https://edudel.nic.in/",
    application_link: null,
    department: "Directorate of Education",
    category: "students",
    target_groups: ["Students", "Children"],
    tags: ["education", "textbooks", "subsidy"],
    required_documents: ["School ID card", "Aadhaar Card", "Bank Account Details (if cash)"],
    min_age: 3,
    max_age: 18,
    gender: null,
    occupation: "student",
    social_category: null,
    has_disability: false,
    max_income: null,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Old Age Pension Scheme (Delhi)",
    title_hi: "वृद्धावस्था पेंशन योजना (दिल्ली)",
    short_description_en: "Financial assistance to senior citizens in Delhi.",
    short_description_hi: "दिल्ली में वरिष्ठ नागरिकों को वित्तीय सहायता।",
    description_en: "Financial support to vulnerable senior citizens residing in Delhi who have no adequate means of subsistence.",
    description_hi: "दिल्ली में रहने वाले कमजोर वरिष्ठ नागरिकों को वित्तीय सहायता जिनके पास निर्वाह का कोई पर्याप्त साधन नहीं है।",
    eligibility_en: "Age 60 or above, resident of Delhi for at least 5 years, family income < Rs 1 Lakh p.a.",
    eligibility_hi: "आयु 60 वर्ष या उससे अधिक, कम से कम 5 वर्षों के लिए दिल्ली का निवासी, पारिवारिक आय < 1 लाख रुपये प्रति वर्ष।",
    benefits_en: "Rs 2,000 per month (60-69 years) and Rs 2,500 per month (70+ years).",
    benefits_hi: "2,000 रुपये प्रति माह (60-69 वर्ष) और 2,500 रुपये प्रति माह (70+ वर्ष)।",
    apply_url: "https://edistrict.delhigovt.nic.in/",
    application_link: "https://edistrict.delhigovt.nic.in/",
    department: "Department of Social Welfare",
    category: "senior_citizens",
    target_groups: ["Senior Citizens"],
    tags: ["pension", "financial-assistance", "elderly"],
    required_documents: ["Age Proof", "Residence Proof (5 years)", "Income Certificate", "Bank Passbook", "Aadhaar Card"],
    min_age: 60,
    max_age: null,
    gender: null,
    occupation: "unemployed",
    social_category: null,
    has_disability: false,
    max_income: 100000,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Widow Pension Scheme (Delhi Pension to Women in Distress)",
    title_hi: "विधवा पेंशन योजना (संकट में फंसी महिलाओं को दिल्ली पेंशन)",
    short_description_en: "Financial aid for widows, divorced, or destitute women.",
    short_description_hi: "विधवाओं, तलाकशुदा या निराश्रित महिलाओं के लिए वित्तीय सहायता।",
    description_en: "Financial assistance to widows, divorced, separated, destitute, or abandoned women with no adequate means of livelihood.",
    description_hi: "विधवाओं, तलाकशुदा, निराश्रित या परित्यक्त महिलाओं को वित्तीय सहायता जिनके पास आजीविका का कोई पर्याप्त साधन नहीं है।",
    eligibility_en: "Resident of Delhi (5 years+), age 18 to 59 years, family income < Rs 1 Lakh p.a.",
    eligibility_hi: "दिल्ली की निवासी (5 वर्ष+), आयु 18 से 59 वर्ष, पारिवारिक आय < 1 लाख रुपये प्रति वर्ष।",
    benefits_en: "Rs 2,500 per month remitted directly to the bank account.",
    benefits_hi: "प्रति माह 2,500 रुपये सीधे बैंक खाते में भेजे गए।",
    apply_url: "https://wcddel.in/",
    application_link: "https://edistrict.delhigovt.nic.in/",
    department: "Department of Women & Child Development",
    category: "women",
    target_groups: ["Widows", "Divorced Women", "Destitute Women"],
    tags: ["pension", "women-empowerment"],
    required_documents: ["Death certificate of husband (if widow)", "Residence Proof", "Income Certificate", "Aadhaar Card", "Bank details"],
    min_age: 18,
    max_age: 59,
    gender: "female",
    occupation: null,
    social_category: null,
    has_disability: false,
    max_income: 100000,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Mukhyamantri COVID-19 Pariwar Aarthik Sahayata Yojana",
    title_hi: "मुख्यमंत्री कोविड-19 परिवार आर्थिक सहायता योजना",
    short_description_en: "Assistance for families who lost a breadwinner to COVID-19.",
    short_description_hi: "उन परिवारों के लिए सहायता जिन्होंने कोविड-19 में कमाने वाले को खो दिया।",
    description_en: "Financial distress relief for families who lost their earning member or any family member due to COVID-19.",
    description_hi: "कोविड-19 के कारण अपने कमाने वाले सदस्य या परिवार के किसी भी सदस्य को खोने वाले परिवारों के लिए वित्तीय संकट राहत।",
    eligibility_en: "Resident of Delhi, death occurred due to COVID-19 in Delhi.",
    eligibility_hi: "दिल्ली का निवासी, दिल्ली में कोविड-19 के कारण मृत्यु हुई।",
    benefits_en: "Ex-gratia of Rs 50,000, and Rs 2,500 monthly pension if breadwinner was lost.",
    benefits_hi: "50,000 रुपये की अनुग्रह राशि, और यदि कमाने वाला खो गया था तो 2,500 रुपये मासिक पेंशन।",
    apply_url: "https://edistrict.delhigovt.nic.in/",
    application_link: "https://edistrict.delhigovt.nic.in/",
    department: "Department of Social Welfare",
    category: "general",
    target_groups: ["COVID Affected Families"],
    tags: ["pension", "relief", "ex-gratia", "covid"],
    required_documents: ["Death Certificate", "COVID positive report", "Aadhaar Card", "Surviving Member Certificate"],
    min_age: null,
    max_age: null,
    gender: null,
    occupation: null,
    social_category: null,
    has_disability: false,
    max_income: null,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Financial Assistance to Persons with Special Needs",
    title_hi: "विशेष आवश्यकता वाले व्यक्तियों को वित्तीय सहायता",
    short_description_en: "Monthly pension for disabled persons in Delhi.",
    short_description_hi: "दिल्ली में विकलांग व्यक्तियों के लिए मासिक पेंशन।",
    description_en: "Financial assistance provided by the Delhi Government to physically and mentally challenged persons to aid their subsistence.",
    description_hi: "शारीरिक और मानसिक रूप से विकलांग व्यक्तियों को उनके निर्वाह में सहायता के लिए दिल्ली सरकार द्वारा प्रदान की जाने वाली वित्तीय सहायता।",
    eligibility_en: "Disability of 40% or more, resident of Delhi for at least 5 years, family income < Rs 1 Lakh p.a.",
    eligibility_hi: "40% या उससे अधिक की विकलांगता, कम से कम 5 वर्षों के लिए दिल्ली का निवासी, पारिवारिक आय < 1 लाख रुपये प्रति वर्ष।",
    benefits_en: "Rs 2,500 per month.",
    benefits_hi: "2,500 रुपये प्रति माह।",
    apply_url: "https://socialwelfare.delhigovt.nic.in/",
    application_link: "https://edistrict.delhigovt.nic.in/",
    department: "Department of Social Welfare",
    category: "disability",
    target_groups: ["Persons with Disabilities"],
    tags: ["pension", "disability", "financial-assistance"],
    required_documents: ["Disability Certificate", "Residence Proof", "Income Certificate", "Aadhaar Card", "Bank Account Details"],
    min_age: 0,
    max_age: null,
    gender: null,
    occupation: null,
    social_category: null,
    has_disability: true,
    max_income: 100000,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Chief Minister's Super Talented Children Scholarship",
    title_hi: "मुख्यमंत्री अति प्रतिभाशाली बाल छात्रवृत्ति",
    short_description_en: "Scholarship and free coaching for super-talented students.",
    short_description_hi: "अति-प्रतिभाशाली छात्रों के लिए छात्रवृत्ति और मुफ्त कोचिंग।",
    description_en: "Identifies super-talented students of class XI and XII in Delhi Govt schools and provides professional coaching for Medical & Engineering entrance.",
    description_hi: "दिल्ली सरकार के स्कूलों में कक्षा 11वीं और 12वीं के अति-प्रतिभाशाली छात्रों की पहचान करता है और मेडिकल और इंजीनियरिंग प्रवेश के लिए पेशेवर कोचिंग प्रदान करता है।",
    eligibility_en: "Students of Class XI/XII in govt schools selected via a screening test.",
    eligibility_hi: "छाँट परीक्षा के माध्यम से चयनित सरकारी स्कूलों में कक्षा 11वीं/12वीं के छात्र।",
    benefits_en: "Free premium coaching for JEE/NEET, study materials, and transport allowance.",
    benefits_hi: "JEE/NEET के लिए मुफ्त प्रीमियम कोचिंग, अध्ययन सामग्री और परिवहन भत्ता।",
    apply_url: "https://edudel.nic.in/",
    application_link: null,
    department: "Directorate of Education",
    category: "students",
    target_groups: ["Meritorious Students"],
    tags: ["education", "scholarship", "coaching", "stem"],
    required_documents: ["School ID", "Marksheets", "Admission Form"],
    min_age: 14,
    max_age: 19,
    gender: null,
    occupation: "student",
    social_category: null,
    has_disability: false,
    max_income: null,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Delhi Swarojgar Yojana",
    title_hi: "दिल्ली स्वरोजगार योजना",
    short_description_en: "Financial aid for setting up self-employment ventures.",
    short_description_hi: "स्वरोजगार उद्यम स्थापित करने के लिए वित्तीय सहायता।",
    description_en: "Provides loans and subsidies to SC/ST/OBC and Minority individuals to set up small businesses and self-employment ventures.",
    description_hi: "छोटे व्यवसाय और स्वरोजगार उद्यम स्थापित करने के लिए SC/ST/OBC और अल्पसंख्यक व्यक्तियों को ऋण और सब्सिडी प्रदान करता है।",
    eligibility_en: "Resident of Delhi for 5 years, SC/ST/OBC/Minority category, age 18-55, income below 3 Lakhs p.a.",
    eligibility_hi: "5 वर्षों के लिए दिल्ली का निवासी, SC/ST/OBC/अल्पसंख्यक श्रेणी, आयु 18-55, आय 3 लाख रुपये प्रति वर्ष से कम।",
    benefits_en: "Term loan up to Rs 5 Lakhs with low interest and margin money subsidy.",
    benefits_hi: "कम ब्याज और मार्जिन मनी सब्सिडी के साथ 5 लाख रुपये तक का सावधि ऋण।",
    apply_url: "https://scstwelfare.delhigovt.nic.in/",
    application_link: "https://edistrict.delhigovt.nic.in/",
    department: "DSFDC (Delhi SC/ST/OBC/Minorities & Handicapped Financial and Development Corp.)",
    category: "small_business",
    target_groups: ["Entrepreneurs", "SC/ST/OBC", "Minorities"],
    tags: ["loan", "business", "self-employment", "subsidy"],
    required_documents: ["Project Report", "Caste Certificate", "Aadhaar Card", "Income Certificate", "Residence Proof"],
    min_age: 18,
    max_age: 55,
    gender: null,
    occupation: "unemployed",
    social_category: "SC/ST/OBC/Minority",
    has_disability: false,
    max_income: 300000,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Mukhyamantri Vidyarthi Pratibha Yojana",
    title_hi: "मुख्यमंत्री विद्यार्थी प्रतिभा योजना",
    short_description_en: "Financial incentives to meritorious students of Class 9, 10, 11, and 12.",
    short_description_hi: "कक्षा 9, 10, 11 और 12 के मेधावी छात्रों को वित्तीय प्रोत्साहन।",
    description_en: "Rewards meritorious SC/ST/OBC/Minority students in Delhi Govt/Aided schools to encourage academic excellence.",
    description_hi: "अकादमिक उत्कृष्टता को प्रोत्साहित करने के लिए दिल्ली सरकार/सहायता प्राप्त स्कूलों में मेधावी SC/ST/OBC/अल्पसंख्यक छात्रों को पुरस्कृत करता है।",
    eligibility_en: "SC/ST/OBC/Minority students of Class 9 to 12 in Delhi with specified minimum marks.",
    eligibility_hi: "विशिष्ट न्यूनतम अंकों के साथ दिल्ली में कक्षा 9 से 12 तक के SC/ST/OBC/अल्पसंख्यक छात्र।",
    benefits_en: "Rs 5,000 to Rs 10,000 depending on the class and secured marks.",
    benefits_hi: "कक्षा और प्राप्त अंकों के आधार पर 5,000 रुपये से 10,000 रुपये तक।",
    apply_url: "https://scstwelfare.delhigovt.nic.in/",
    application_link: "https://edistrict.delhigovt.nic.in/",
    department: "Department for the Welfare of SC/ST/OBC",
    category: "students",
    target_groups: ["Meritorious Students", "SC/ST/OBC"],
    tags: ["scholarship", "education", "reward"],
    required_documents: ["Caste Certificate", "Previous Year Marksheet", "Aadhaar Card", "Bank Account Details"],
    min_age: 13,
    max_age: 19,
    gender: null,
    occupation: "student",
    social_category: "SC/ST/OBC/Minority",
    has_disability: false,
    max_income: 800000,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "DBSE Free Tablet Scheme",
    title_hi: "DBSE मुफ्त टैबलेट योजना",
    short_description_en: "Distribution of free tablets to students of Delhi Board schools.",
    short_description_hi: "दिल्ली बोर्ड के स्कूलों के छात्रों को मुफ्त टैबलेट का वितरण।",
    description_en: "Free tablets provided to students enrolled in Schools of Specialized Excellence under DBSE to aid in digital learning.",
    description_hi: "डिजिटल लर्निंग में सहायता के लिए DBSE के तहत स्कूल ऑफ स्पेशलाइज्ड एक्सीलेंस में नामांकित छात्रों को मुफ्त टैबलेट प्रदान किए गए।",
    eligibility_en: "Students correctly enrolled in Class 9-12 in a School of Specialized Excellence.",
    eligibility_hi: "स्कूल ऑफ स्पेशलाइज्ड एक्सीलेंस में कक्षा 9-12 में सही ढंग से नामांकित छात्र।",
    benefits_en: "Free tablet with internet data capability.",
    benefits_hi: "इंटरनेट डेटा क्षमता के साथ मुफ्त टैबलेट।",
    apply_url: "https://edudel.nic.in/",
    application_link: null,
    department: "Delhi Board of School Education",
    category: "students",
    target_groups: ["Students of SOSE"],
    tags: ["education", "digital-learning", "tablet"],
    required_documents: ["School Admission Proof", "Student ID"],
    min_age: 13,
    max_age: 19,
    gender: null,
    occupation: "student",
    social_category: null,
    has_disability: false,
    max_income: null,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Mukhyamantri Teerth Yatra Yojana",
    title_hi: "मुख्यमंत्री तीर्थ यात्रा योजना",
    short_description_en: "Free pilgrimage for senior citizens of Delhi.",
    short_description_hi: "दिल्ली के वरिष्ठ नागरिकों के लिए मुफ्त तीर्थ यात्रा।",
    description_en: "Enables senior citizens of Delhi to go on a free pilgrimage to various spiritual and religious destinations across India, accompanied by one attendant.",
    description_hi: "दिल्ली के वरिष्ठ नागरिकों को पूरे भारत में विभिन्न आध्यात्मिक और धार्मिक स्थलों की मुफ्त तीर्थयात्रा पर जाने में सक्षम बनाता है, साथ में एक परिचारक भी होता है।",
    eligibility_en: "Resident of Delhi, 60 years or above, not an employee of Central/State Govt/Local bodies.",
    eligibility_hi: "दिल्ली का निवासी, 60 वर्ष या उससे अधिक, केंद्र/राज्य सरकार/स्थानीय निकायों का कर्मचारी नहीं होना चाहिए।",
    benefits_en: "Free travel, AC accommodation, meals, insurance, and medical facilities. Allowed 1 attendant above 21 years.",
    benefits_hi: "मुफ्त यात्रा, एसी आवास, भोजन, बीमा और चिकित्सा सुविधाएं। 21 वर्ष से ऊपर के 1 परिचारक की अनुमति है।",
    apply_url: "https://edistrict.delhigovt.nic.in/",
    application_link: "https://edistrict.delhigovt.nic.in/",
    department: "Revenue Department",
    category: "senior_citizens",
    target_groups: ["Senior Citizens"],
    tags: ["pilgrimage", "travel", "elderly"],
    required_documents: ["Voter ID Card", "Medical Fitness Certificate", "Aadhaar Card", "Attendant's ID"],
    min_age: 60,
    max_age: null,
    gender: null,
    occupation: null,
    social_category: null,
    has_disability: false,
    max_income: null,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Financial Assistance for Marriage of Pro-poor Widows' Daughters",
    title_hi: "गरीब और कमजोर विधवाओं की बेटियों की शादी के लिए वित्तीय सहायता",
    short_description_en: "Financial aid to widows for their daughter's marriage.",
    short_description_hi: "विधवाओं को अपनी बेटी की शादी के लिए वित्तीय सहायता।",
    description_en: "A one-time grant to poor widows, orphan girls, or destitute women to help meet the expenses of their daughter's marriage.",
    description_hi: "गरीब विधवाओं, अनाथ लड़कियों या निराश्रित महिलाओं को उनकी बेटी की शादी के खर्चों को पूरा करने में मदद करने के लिए एकमुश्त अनुदान।",
    eligibility_en: "Resident of Delhi (5+ years), family income < Rs 1 Lakh p.a., girl must be 18+.",
    eligibility_hi: "दिल्ली की निवासी (5+ वर्ष), पारिवारिक आय < 1 लाख रुपये प्रति वर्ष, लड़की की उम्र 18+ होनी चाहिए।",
    benefits_en: "One-time financial assistance of Rs 30,000.",
    benefits_hi: "30,000 रुपये की एकमुश्त वित्तीय सहायता।",
    apply_url: "https://wcddel.in/",
    application_link: "https://edistrict.delhigovt.nic.in/",
    department: "Department of Women & Child Development",
    category: "women",
    target_groups: ["Widows", "Poor Families"],
    tags: ["marriage", "financial-assistance", "women"],
    required_documents: ["Age proof of bride (18+)", "Marriage Card", "Income Certificate", "Residence Proof", "Widow Certificate"],
    min_age: 18,
    max_age: null,
    gender: "female",
    occupation: null,
    social_category: null,
    has_disability: false,
    max_income: 100000,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Delhi State Award for Persons with Disabilities",
    title_hi: "विकलांग व्यक्तियों के लिए दिल्ली राज्य पुरस्कार",
    short_description_en: "Awards to outstanding disabled employees/entrepreneurs.",
    short_description_hi: "उत्कृष्ट विकलांग कर्मचारियों/उद्यमियों को पुरस्कार।",
    description_en: "An annual award by the Delhi Govt to recognize the outstanding achievements and contributions of Persons with Disabilities, and to their employers.",
    description_hi: "विकलांग व्यक्तियों और उनके नियोक्ताओं की उत्कृष्ट उपलब्धियों और योगदान को मान्यता देने के लिए दिल्ली सरकार द्वारा एक वार्षिक पुरस्कार।",
    eligibility_en: "Differently-abled individuals resident of Delhi doing exemplary work in their fields.",
    eligibility_hi: "अपने क्षेत्र में अनुकरणीय कार्य करने वाले दिल्ली के निवासी अलग-अलग विकलांग व्यक्ति।",
    benefits_en: "Cash award, citation, and certificate.",
    benefits_hi: "नकद पुरस्कार, प्रशस्ति पत्र और प्रमाण पत्र।",
    apply_url: "https://socialwelfare.delhigovt.nic.in/",
    application_link: null,
    department: "Department of Social Welfare",
    category: "disability",
    target_groups: ["Persons with Disabilities", "Entrepreneurs", "Employers"],
    tags: ["award", "recognition", "disability"],
    required_documents: ["Disability Certificate", "Work Profile/Achievements", "Aadhaar Card", "Nominations"],
    min_age: 18,
    max_age: null,
    gender: null,
    occupation: null,
    social_category: null,
    has_disability: true,
    max_income: null,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Unemployment Allowance to Persons with Disabilities",
    title_hi: "विकलांग व्यक्तियों को बेरोजगारी भत्ता",
    short_description_en: "Allowance for registered disabled unemployed youths.",
    short_description_hi: "पंजीकृत विकलांग बेरोजगार युवाओं के लिए भत्ता।",
    description_en: "Financial assistance provided to persons with disabilities who are registered with the special employment exchange but are unemployed.",
    description_hi: "विशेष रोजगार विनिमय में पंजीकृत लेकिन बेरोजगार विकलांग व्यक्तियों को वित्तीय सहायता।",
    eligibility_en: "Disability > 40%, registered in Employment Exchange for > 2 years, Age 18-50.",
    eligibility_hi: "विकलांगता > 40%, रोजगार कार्यालय में 2 वर्ष से अधिक समय से पंजीकृत, आयु 18-50।",
    benefits_en: "Rs 1,500 to Rs 2,500 depending on qualifications.",
    benefits_hi: "योग्यता के आधार पर 1,500 रुपये से 2,500 रुपये।",
    apply_url: "https://socialwelfare.delhigovt.nic.in/",
    application_link: "https://edistrict.delhigovt.nic.in/",
    department: "Department of Social Welfare",
    category: "disability",
    target_groups: ["Unemployed Youth", "Persons with Disabilities"],
    tags: ["unemployment", "allowance", "disability"],
    required_documents: ["Disability Certificate", "Employment Exchange Registration", "Aadhaar Card", "Education Proof"],
    min_age: 18,
    max_age: 50,
    gender: null,
    occupation: "unemployed",
    social_category: null,
    has_disability: true,
    max_income: null,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Delhi Kissan Mitra Yojana",
    title_hi: "दिल्ली किसान मित्र योजना",
    short_description_en: "Support to farmers for better agriculture practices.",
    short_description_hi: "बेहतर कृषि विधियों के लिए किसानों को सहायता।",
    description_en: "Aimed at assisting farmers in Delhi NCR to adopt modern agricultural practices, arrange soil testing, and provide seeds.",
    description_hi: "दिल्ली एनसीआर के किसानों को आधुनिक कृषि पद्धतियों को अपनाने, मिट्टी परीक्षण की व्यवस्था करने और बीज उपलब्ध कराने में सहायता करना।",
    eligibility_en: "Must be a registered farmer in the Delhi region, owning agricultural land.",
    eligibility_hi: "दिल्ली क्षेत्र में एक पंजीकृत किसान होना चाहिए, जिसके पास कृषि भूमि हो।",
    benefits_en: "Free soil testing, subsidized seeds, and technical guidance.",
    benefits_hi: "मुफ्त मिट्टी परीक्षण, रियायती बीज और तकनीकी मार्गदर्शन।",
    apply_url: "https://development.delhigovt.nic.in/",
    application_link: null,
    department: "Development Department",
    category: "farmers",
    target_groups: ["Farmers", "Agricultural Workers"],
    tags: ["agriculture", "seeds", "soil-testing"],
    required_documents: ["Land Records (Khasra/Khatauni)", "Aadhaar Card", "Bank details"],
    min_age: 18,
    max_age: null,
    gender: null,
    occupation: "farmer",
    social_category: null,
    has_disability: false,
    max_income: null,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Mukhyamantri Krishi Ashirwad Yojana (Delhi Draft)",
    title_hi: "मुख्यमंत्री कृषि आशीर्वाद योजना (दिल्ली)",
    short_description_en: "Financial assistance per acre for marginal farmers.",
    short_description_hi: "सीमांत किसानों के लिए प्रति एकड़ वित्तीय सहायता।",
    description_en: "Provides direct financial assistance to small and marginal farmers per acre to acquire seeds, fertilizers, and equipment before the cropping season.",
    description_hi: "फसल के मौसम से पहले बीज, उर्वरक और उपकरण प्राप्त करने के लिए छोटे और सीमांत किसानों को प्रति एकड़ प्रत्यक्ष वित्तीय सहायता प्रदान करता है।",
    eligibility_en: "Farmers owning up to 5 acres of agricultural land in Delhi area.",
    eligibility_hi: "दिल्ली क्षेत्र में 5 एकड़ तक कृषि भूमि के मालिक किसान।",
    benefits_en: "Rs 5,000 per acre (max cap up to 5 acres).",
    benefits_hi: "5,000 रुपये प्रति एकड़ (अधिकतम 5 एकड़ तक की सीमा)।",
    apply_url: "https://development.delhigovt.nic.in/",
    application_link: null,
    department: "Development Department",
    category: "farmers",
    target_groups: ["Small and Marginal Farmers"],
    tags: ["agriculture", "subsidy", "financial-assistance"],
    required_documents: ["Land ownership documents", "Aadhaar Card", "Bank passbook"],
    min_age: 18,
    max_age: null,
    gender: null,
    occupation: "farmer",
    social_category: null,
    has_disability: false,
    max_income: null,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Financial Assistance to Construction Workers",
    title_hi: "निर्माण श्रमिकों को वित्तीय सहायता",
    short_description_en: "Cash relief/bonus for registered building and construction workers.",
    short_description_hi: "पंजीकृत भवन एवं निर्माण श्रमिकों के लिए नकद राहत/बोनस।",
    description_en: "Periodic financial assistance (often distributed during Diwali, pollution bans, or calamities) to registered construction workers in Delhi.",
    description_hi: "दिल्ली में पंजीकृत निर्माण श्रमिकों को समय-समय पर वित्तीय सहायता (अक्सर दीवाली, प्रदूषण प्रतिबंध या आपदाओं के दौरान वितरित)।",
    eligibility_en: "Must be a registered construction worker with the DBOCWWB.",
    eligibility_hi: "DBOCWWB के साथ पंजीकृत निर्माण श्रमिक होना चाहिए।",
    benefits_en: "Rs 5,000 grant during ban on construction/calamities/festivals.",
    benefits_hi: "निर्माण/आपदाओं/त्योहारों पर प्रतिबंध के दौरान 5,000 रुपये का अनुदान।",
    apply_url: "https://dbocwwb.delhi.gov.in/",
    application_link: "https://edistrict.delhigovt.nic.in/",
    department: "Delhi Building and Other Construction Workers Welfare Board",
    category: "workers",
    target_groups: ["Construction Workers", "Laborers"],
    tags: ["labor", "allowance", "welfare", "construction"],
    required_documents: ["Labour Card (DBOCWWB Registration)", "Bank Account Details", "Aadhaar Card"],
    min_age: 18,
    max_age: 60,
    gender: null,
    occupation: "construction worker",
    social_category: null,
    has_disability: false,
    max_income: null,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Maternity Benefit Scheme for Construction Workers",
    title_hi: "निर्माण श्रमिकों के लिए मातृत्व लाभ योजना",
    short_description_en: "Maternity benefits for female registered construction workers.",
    short_description_hi: "महिला पंजीकृत निर्माण श्रमिकों के लिए मातृत्व लाभ।",
    description_en: "Provides maternity benefits to registered female construction workers or to the wives of male registered workers to cover medical expenses and wage loss.",
    description_hi: "चिकित्सा व्यय और वेतन हानि को कवर करने के लिए महिला पंजीकृत निर्माण श्रमिकों या पुरुष पंजीकृत श्रमिकों की पत्नियों को मातृत्व लाभ प्रदान करता है।",
    eligibility_en: "Registered female construction worker or wife of a registered worker. Max two children.",
    eligibility_hi: "पंजीकृत महिला निर्माण श्रमिक या पंजीकृत पुरुष श्रमिक की पत्नी। अधिकतम दो बच्चे।",
    benefits_en: "Rs 30,000 financial assistance.",
    benefits_hi: "30,000 रुपये वित्तीय सहायता।",
    apply_url: "https://dbocwwb.delhi.gov.in/",
    application_link: "https://edistrict.delhigovt.nic.in/",
    department: "DBOCWWB",
    category: "workers",
    target_groups: ["Female Construction Workers"],
    tags: ["maternity", "healthcare", "labor", "women"],
    required_documents: ["Labour Card", "Medical records of delivery", "Birth Certificate of child", "Aadhaar Card"],
    min_age: 18,
    max_age: 50,
    gender: null,
    occupation: "construction worker",
    social_category: null,
    has_disability: false,
    max_income: null,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Pension for Construction Workers",
    title_hi: "निर्माण श्रमिकों के लिए पेंशन",
    short_description_en: "Pension for workers after age 60.",
    short_description_hi: "60 वर्ष की आयु के बाद श्रमिकों के लिए पेंशन।",
    description_en: "Monthly pension given to registered construction workers in Delhi after they reach the age of 60.",
    description_hi: "60 वर्ष की आयु तक पहुंचने के बाद दिल्ली में पंजीकृत निर्माण श्रमिकों को मासिक पेंशन दी जाती है।",
    eligibility_en: "Registered with DBOCWWB and completed 60 years of age.",
    eligibility_hi: "DBOCWWB के साथ पंजीकृत और 60 वर्ष की आयु पूरी कर चुके हैं।",
    benefits_en: "Rs 3,000 per month pension.",
    benefits_hi: "3,000 रुपये प्रति माह पेंशन।",
    apply_url: "https://dbocwwb.delhi.gov.in/",
    application_link: "https://edistrict.delhigovt.nic.in/",
    department: "DBOCWWB",
    category: "workers",
    target_groups: ["Senior Construction Workers"],
    tags: ["pension", "elderly", "labor"],
    required_documents: ["Labour Card", "Age Proof", "Aadhaar Card", "Life Certificate"],
    min_age: 60,
    max_age: null,
    gender: null,
    occupation: "construction worker",
    social_category: null,
    has_disability: false,
    max_income: null,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Tool Kit and Bicycle scheme for Construction Workers",
    title_hi: "निर्माण श्रमिकों के लिए टूल किट और साइकिल योजना",
    short_description_en: "Financial assistance to buy tools and a bicycle.",
    short_description_hi: "उपकरण और साइकिल खरीदने के लिए वित्तीय सहायता।",
    description_en: "Financial aid provided to registered building and other construction workers to purchase toolkits necessary for their trade and a bicycle for commuting.",
    description_hi: "पंजीकृत भवन और अन्य निर्माण श्रमिकों को उनके व्यापार के लिए आवश्यक टूलकिट और आने-जाने के लिए साइकिल खरीदने के लिए दी जाने वाली वित्तीय सहायता।",
    eligibility_en: "Must be active registered construction worker with DBOCWWB.",
    eligibility_hi: "DBOCWWB के साथ सक्रिय पंजीकृत निर्माण श्रमिक होना चाहिए।",
    benefits_en: "Rs 20,000 for Tool Kit and Rs 3,000 for Bicycle.",
    benefits_hi: "टूल किट के लिए 20,000 रुपये और साइकिल के लिए 3,000 रुपये।",
    apply_url: "https://dbocwwb.delhi.gov.in/",
    application_link: "https://edistrict.delhigovt.nic.in/",
    department: "DBOCWWB",
    category: "workers",
    target_groups: ["Construction Workers"],
    tags: ["toolkit", "bicycle", "labor", "equipment"],
    required_documents: ["Labour Card", "Slip/Bill of purchase", "Aadhaar Card"],
    min_age: 18,
    max_age: 60,
    gender: null,
    occupation: "construction worker",
    social_category: null,
    has_disability: false,
    max_income: null,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Delhi Startup Policy Incentives",
    title_hi: "दिल्ली स्टार्टअप नीति प्रोत्साहन",
    short_description_en: "Subsidies, rent support, and loans for startups.",
    short_description_hi: "स्टार्टअप के लिए सब्सिडी, किराया सहायता और ऋण।",
    description_en: "Under the Delhi Startup Policy, the government supports entrepreneurs by providing collateral-free loans, office rent subsidies, and a portion of employees' salaries.",
    description_hi: "दिल्ली स्टार्टअप नीति के तहत, सरकार उद्यमियों को संपार्श्विक-मुक्त ऋण, कार्यालय किराया सब्सिडी और कर्मचारियों के वेतन का एक हिस्सा प्रदान करके समर्थन करती है।",
    eligibility_en: "Registered startup under DPIIT, operating in Delhi, generating employment.",
    eligibility_hi: "DPIIT के तहत पंजीकृत स्टार्टअप, दिल्ली में कार्यरत, रोजगार पैदा कर रहा हो।",
    benefits_en: "Up to 50% office rent subsidy, loan guarantees, and financial grants for R&D.",
    benefits_hi: "50% तक कार्यालय किराया सब्सिडी, ऋण गारंटी और R&D के लिए वित्तीय अनुदान।",
    apply_url: "https://ddc.delhi.gov.in/",
    application_link: null,
    department: "Dialogue and Development Commission of Delhi",
    category: "small_business",
    target_groups: ["Startups", "Entrepreneurs", "Youth"],
    tags: ["startup", "business", "innovation", "loan", "subsidy"],
    required_documents: ["Startup India Registration", "Company Details", "Project Pitch", "GST Registration", "Bank Details"],
    min_age: 18,
    max_age: null,
    gender: null,
    occupation: "entrepreneur",
    social_category: null,
    has_disability: false,
    max_income: null,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Subsidized Loan for E-Rickshaw",
    title_hi: "ई-रिक्शा के लिए रियायती ऋण",
    short_description_en: "Subsidies on e-rickshaw purchase to promote green transport.",
    short_description_hi: "हरित परिवहन को बढ़ावा देने के लिए ई-रिक्शा खरीद पर सब्सिडी।",
    description_en: "To fight pollution and support self-employment, DSFDC provides loans and Rs 30,000 subsidy on the purchase of E-Rickshaws by SC/ST/OBC and Minority individuals.",
    description_hi: "प्रदूषण से लड़ने और स्वरोजगार को बढ़ावा देने के लिए, DSFDC SC/ST/OBC और अल्पसंख्यक व्यक्तियों को ई-रिक्शा की खरीद पर ऋण और 30,000 रुपये की सब्सिडी प्रदान करता है।",
    eligibility_en: "Resident of Delhi (5 years), SC/ST/OBC/Minority, must possess driving license/badge.",
    eligibility_hi: "दिल्ली का निवासी (5 वर्ष), SC/ST/OBC/अल्पसंख्यक, ड्राइविंग लाइसेंस/बैज होना चाहिए।",
    benefits_en: "Rs 30,000 subsidy, easy EMI loans for the rest of the cost.",
    benefits_hi: "30,000 रुपये की सब्सिडी, शेष लागत के लिए आसान EMI ऋण।",
    apply_url: "https://scstwelfare.delhigovt.nic.in/",
    application_link: "https://edistrict.delhigovt.nic.in/",
    department: "DSFDC",
    category: "small_business",
    target_groups: ["Drivers", "Unemployed Youth", "SC/ST/OBC"],
    tags: ["loan", "EV", "e-rickshaw", "transport"],
    required_documents: ["Aadhaar", "Driving License", "Caste Certificate", "Quotation of E-Rickshaw"],
    min_age: 18,
    max_age: 60,
    gender: null,
    occupation: "driver",
    social_category: "SC/ST/OBC/Minority",
    has_disability: false,
    max_income: 300000,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Mukhyamantri Mahila Samman Yojana",
    title_hi: "मुख्यमंत्री महिला सम्मान योजना",
    short_description_en: "Monthly Rs 1,000 allowance for every adult woman.",
    short_description_hi: "प्रत्येक वयस्क महिला के लिए मासिक 1,000 रुपये का भत्ता।",
    description_en: "A newly announced scheme allocating Rs 1,000 per month to every woman in Delhi above 18 years of age who does not pay income tax or hold a government job.",
    description_hi: "एक नई घोषित योजना जिसमें 18 वर्ष से अधिक आयु की दिल्ली की प्रत्येक महिला को 1,000 रुपये प्रति माह देने का प्रावधान है जो आयकर का भुगतान नहीं करती है या सरकारी नौकरी नहीं करती है।",
    eligibility_en: "Woman $>=$ 18 years, resident of Delhi, not an income taxpayer, not receiving any other government pension.",
    eligibility_hi: "महिला >= 18 वर्ष, दिल्ली की निवासी, आयकर दाता नहीं, कोई अन्य सरकारी पेंशन प्राप्त नहीं कर रही हो।",
    benefits_en: "Rs 1,000 transferred every month directly to the bank account.",
    benefits_hi: "हर महीने 1,000 रुपये सीधे बैंक खाते में ट्रांसफर किए जाएंगे।",
    apply_url: "https://delhi.gov.in/",
    application_link: null,
    department: "Department of Women and Child Development",
    category: "women",
    target_groups: ["Adult Women", "Homemakers", "Students"],
    tags: ["financial-assistance", "women-empowerment", "allowance"],
    required_documents: ["Aadhaar Card", "Voter ID Card", "Bank Account linked with Aadhaar", "Self Declaration"],
    min_age: 18,
    max_age: null,
    gender: "female",
    occupation: null,
    social_category: null,
    has_disability: false,
    max_income: null,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Delhi Free Bus Ride Scheme for Women",
    title_hi: "महिलाओं के लिए दिल्ली मुफ्त बस यात्रा योजना",
    short_description_en: "Free travel for women in DTC and Cluster buses.",
    short_description_hi: "डीटीसी और क्लस्टर बसों में महिलाओं के लिए मुफ्त यात्रा।",
    description_en: "Provides free travel to women passengers in all non-AC and AC DTC and Delhi Transit (Cluster) buses through Pink Tickets.",
    description_hi: "पिंक टिकट के माध्यम से सभी नॉन-एसी और एसी डीटीसी और दिल्ली ट्रांजिट (क्लस्टर) बसों में महिला यात्रियों को मुफ्त यात्रा प्रदान करता है।",
    eligibility_en: "Any woman traveling in Delhi local buses.",
    eligibility_hi: "दिल्ली की स्थानीय बसों में सफर करने वाली कोई भी महिला।",
    benefits_en: "100% fare waiver via Pink Ticket for single journey.",
    benefits_hi: "एकल यात्रा के लिए पिंक टिकट के माध्यम से 100% किराया छूट।",
    apply_url: "https://dtc.delhi.gov.in/",
    application_link: null,
    department: "Transport Department",
    category: "women",
    target_groups: ["Women Commuters"],
    tags: ["transport", "free-travel", "women"],
    required_documents: ["None required (issued by conductor)"],
    min_age: 0,
    max_age: null,
    gender: "female",
    occupation: null,
    social_category: null,
    has_disability: false,
    max_income: null,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Safai Karamchari Financial Assistance",
    title_hi: "सफाई कर्मचारी वित्तीय सहायता",
    short_description_en: "Assistance to sanitation workers for hazardous work or injury.",
    short_description_hi: "खतरनाक काम या चोट के लिए सफाई कर्मचारियों को सहायता।",
    description_en: "Provides insurance, medical coverage, and ex-gratia to Safai Karamcharis undertaking hazardous cleaning tasks or injured during work.",
    description_hi: "खतरनाक सफाई कार्य करने वाले या काम के दौरान घायल होने वाले सफाई कर्मचारियों को बीमा, चिकित्सा कवरेज और अनुग्रह राशि प्रदान करता है।",
    eligibility_en: "Employed as a sanitation worker/Safai Karamchari in Delhi.",
    eligibility_hi: "दिल्ली में सफाई কর্মী/सफाई कर्मचारी के रूप में कार्यरत।",
    benefits_en: "Ex-gratia up to Rs 10 Lakh in case of death during hazardous cleaning, and free medical treatment.",
    benefits_hi: "खतरनाक सफाई के दौरान मृत्यु की स्थिति में 10 लाख रुपये तक की अनुग्रह राशि, और मुफ्त चिकित्सा उपचार।",
    apply_url: "https://djb.delhigovt.nic.in/",
    application_link: null,
    department: "Delhi Jal Board / MCD",
    category: "workers",
    target_groups: ["Sanitation Workers"],
    tags: ["hazardous-work", "sanitation", "insurance", "labor"],
    required_documents: ["Employee ID", "FIR / Medical Report", "Dependents' Aadhaar"],
    min_age: 18,
    max_age: 60,
    gender: null,
    occupation: "sanitation worker",
    social_category: null,
    has_disability: false,
    max_income: null,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Transport Subsidy Scheme for Farmers",
    title_hi: "किसानों के लिए परिवहन सब्सिडी योजना",
    short_description_en: "Subsidy on transportation of agricultural produce.",
    short_description_hi: "कृषि उपज के परिवहन पर सब्सिडी।",
    description_en: "Aims to help farmers transport their produce from the field to the mandis (markets) by reimbursing a percentage of transport costs.",
    description_hi: "किसानों को परिवहन लागत के एक प्रतिशत की प्रतिपूर्ति करके उनकी उपज को खेत से मंडियों (बाजारों) तक ले जाने में मदद करना है।",
    eligibility_en: "Small and marginal farmers of Delhi bringing produce to APMC mandis.",
    eligibility_hi: "एपीएमसी मंडियों में उपज लाने वाले दिल्ली के छोटे और सीमांत किसान।",
    benefits_en: "Up to 50% subsidy on the cost of transportation.",
    benefits_hi: "परिवहन की लागत पर 50% तक की सब्सिडी।",
    apply_url: "https://development.delhigovt.nic.in/",
    application_link: null,
    department: "Development Department (APMC)",
    category: "farmers",
    target_groups: ["Farmers"],
    tags: ["agriculture", "transport", "subsidy", "market"],
    required_documents: ["APMC Market Receipt (J-Form)", "Aadhaar Card", "Bank Account"],
    min_age: 18,
    max_age: null,
    gender: null,
    occupation: "farmer",
    social_category: null,
    has_disability: false,
    max_income: null,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Agriculture Equipment Subsidy Scheme",
    title_hi: "कृषि उपकरण सब्सिडी योजना",
    short_description_en: "Subsidy for buying tractors and modern farming tools.",
    short_description_hi: "ट्रैक्टर और आधुनिक कृषि उपकरण खरीदने के लिए सब्सिडी।",
    description_en: "Provides financial aid to farmers to mechanize their farming by subsidizing the purchase of tractors, rotavators, and harvesters.",
    description_hi: "ट्रैक्टर, रोटावेटर और हार्वेस्टर की खरीद पर सब्सिडी देकर किसानों को अपनी खेती को यंत्रीकृत करने के लिए वित्तीय सहायता प्रदान करता है।",
    eligibility_en: "Registered farmer owning land in Delhi.",
    eligibility_hi: "दिल्ली में जमीन का मालिक पंजीकृत किसान।",
    benefits_en: "Up to 30-40% subsidy on the cost of approved agricultural equipment.",
    benefits_hi: "अनुमोदित कृषि उपकरणों की लागत पर 30-40% तक की सब्सिडी।",
    apply_url: "https://development.delhigovt.nic.in/",
    application_link: null,
    department: "Development Department",
    category: "farmers",
    target_groups: ["Farmers"],
    tags: ["agriculture", "equipment", "subsidy", "loans"],
    required_documents: ["Land Records", "Equipment Quotation", "Aadhaar Card", "Bank Details"],
    min_age: 18,
    max_age: null,
    gender: null,
    occupation: "farmer",
    social_category: null,
    has_disability: false,
    max_income: null,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Special School Education Scheme for Disabled Children",
    title_hi: "विकलांग बच्चों के लिए विशेष स्कूल शिक्षा योजना",
    short_description_en: "Free education and special aids in schools.",
    short_description_hi: "स्कूलों में मुफ्त शिक्षा और विशेष सहायता।",
    description_en: "Provides inclusive education, special educators, and learning aids/appliances to Children with Special Needs (CwSN) in govt schools.",
    description_hi: "सरकारी स्कूलों में विशेष आवश्यकता वाले बच्चों (CwSN) को समावेशी शिक्षा, विशेष शिक्षक और शिक्षण सहायता/उपकरण प्रदान करता है।",
    eligibility_en: "Children with disabilities studying in Delhi government schools.",
    eligibility_hi: "दिल्ली के सरकारी स्कूलों में पढ़ने वाले विकलांग बच्चे।",
    benefits_en: "Free uniform, books, transport allowance, escorts, and assistive devices like wheelchairs or hearing aids.",
    benefits_hi: "मुफ्त गणवेश, किताबें, परिवहन भत्ता, एस्कॉर्ट्स और व्हीलचेयर या श्रवण यंत्र जैसे सहायक उपकरण।",
    apply_url: "https://edudel.nic.in/",
    application_link: null,
    department: "Directorate of Education",
    category: "disability",
    target_groups: ["Children with Disabilities", "Students"],
    tags: ["education", "disability", "assistive-devices", "school"],
    required_documents: ["Child's Disability Certificate", "School ID", "Medical Assessment"],
    min_age: 4,
    max_age: 18,
    gender: null,
    occupation: "student",
    social_category: null,
    has_disability: true,
    max_income: null,
    deadline: null,
    is_active: true,
  },
  {
    title_en: "Pradhan Mantri Fasal Bima Yojana (Delhi)",
    title_hi: "प्रधानमंत्री फसल बीमा योजना (दिल्ली)",
    short_description_en: "Crop insurance to protect farmers against natural calamities.",
    short_description_hi: "किसानों को प्राकृतिक आपदाओं से बचाने के लिए फसल बीमा।",
    description_en: "A central scheme implemented by the Delhi govt to provide insurance coverage and financial support to farmers in the event of failure of notified crops due to natural calamities, pests or diseases.",
    description_hi: "प्राकृतिक आपदाओं, कीटों या बीमारियों के कारण अधिसूचित फसलों की विफलता की स्थिति में किसानों को बीमा कवरेज और वित्तीय सहायता प्रदान करने के लिए दिल्ली सरकार द्वारा लागू की गई एक केंद्रीय योजना।",
    eligibility_en: "All farmers growing notified crops in notified areas of Delhi.",
    eligibility_hi: "दिल्ली के अधिसूचित क्षेत्रों में अधिसूचित फसलें उगाने वाले सभी किसान।",
    benefits_en: "Risk coverage and compensation against crop loss. Premium is highly subsidized.",
    benefits_hi: "फसल के नुकसान के खिलाफ जोखिम कवरेज और मुआवजा। प्रीमियम पर भारी सब्सिडी दी जाती है।",
    apply_url: "https://pmfby.gov.in/",
    application_link: "https://pmfby.gov.in/",
    department: "Department of Agriculture and Farmers Welfare",
    category: "farmers",
    target_groups: ["Farmers"],
    tags: ["insurance", "agriculture", "financial-security", "crops"],
    required_documents: ["Land Records", "Sowing Certificate", "Bank Account Details", "Aadhaar Card"],
    min_age: 18,
    max_age: null,
    gender: null,
    occupation: "farmer",
    social_category: null,
    has_disability: false,
    max_income: null,
    deadline: null,
    is_active: true,
  }
];